---
title: "Day 1: Introduction to omics technologies"
author: "Wen Zhong"
date: today
---

::: {.callout-tip}

### Learning objectives  
The field of omic data analysis has been rapidly evolving during the last few decades.
Moreover, the importance of bioinformatics in biomedical research has steadily continued to increase, becoming an almost a required skill for any researcher in the field.
Throughout this module, the students will:

- Know lanscape of omic technologies
- Learn which omic may be more suitable for a given research question.
- Learn how to analyze several types of omics.
:::

### Lectures

#### [9:00-9:50] Lecture 1: Course introduction and omics landscape

**Speaker: Wen Zhong**

The first lecture of the course will introduce the course and provide a brief overview of the evolution of omics technologies, including sequencing, mass spectrometry, and antibody-based techniques.


#### [10:00-10:50] Lecture 2: Cutting-edge technologies in the Swedish molecular diagnostics landscape

**Speaker: Colum Walsh**

Dr. Colum Walsh, current Director of the Clinical Genomics Platform at SciLifeLab, will present the facilities and cutting-edge technologies available to researchers in Sweden, including genomics, proteomics, metabolomics, bioimaging, and bioinformatics


#### [10:50-11:00] Break


#### [11:00-11:30] Lecture 3: Sequencing technologies

**Speaker: Jyotirmoy Das**

This lecture will focus on modern high-throughput sequencing techniques, with applications to DNA, RNA and epigenetic sequencing.


#### [11:30-12:00] Lecture 4: Proteome and metabolome technologies

**Speaker: Wen Zhong**

This lecture will present different technolgies that can be used to generate proteomics and metabolomics data, including mass spectrometry, antibody-based (*e.g.*, Olink) and aptamer-based (*e.g.* SOMAScan).

### Workshops 

#### [13:00-16:00] Omics data, visualization, processing

**Instructor: Jyotirmoy Das**

This workshop introduces omics data and guides the students through essential steps of processing, analysis, and visualization. 
Attendees will learn how to handle epigenetic and proteomics datasets using modern computational tools.


#### [13:00-16:00 cont.] MethylR, CompleteOlink and OlinkWrapper, shiny-WGCNA

**Instructor: Jyotirmoy Das**

MethylR is an R-based tool designed for the analysis and visualization of DNA methylation data, including differential methylation and functional annotation. 
CompleteOlink and OlinkWrapper provide streamlined pipelines for processing, quality control, and analysis of Olink proteomics data, enabling efficient handling of large-scale protein expression datasets.  
Weighted correlation network analysis (WGCNA) is a method to identify groups of highly correlated genes and study their relatoinhips to external traits.
