---
title: "Day 3: AI & ML techniques in biomedical research"
author: "Wen Zhong"
date: today
---

::: {.callout-tip}

### Learning objectives

- Explain the principles, capabilities, and limitations of key AI and machine learning (ML) techniques in biomedical research.
- Evaluate and select appropriate AI/ML approaches for specific biomedical and precision health applications.
 
:::

### Lectures

#### [09:00-10:30] Lecture 1: Network medicine tools for data-driven health 

**Speaker: Mika Gustafsson**

The lecture introduces network models (e.g., deep neural network) and their applications in biomedical research.

#### [10:30-10:45] Break 

#### [10:45-12:00] Lecture 2: Generative AI for Omics analysis

**Speaker: Wen Zhong**

The lecture focuses on an introduction to machine learning methods, and generative AI (e.g., Transformer) and their application in biomedical research.

 
#### [12:00-13:00] Lunch break 

### Workshop

#### [13:00-14:00] Workshop 1: Classical ML methods 

**Workshop instructor: Xingyue Wang**

The workshop aims to understand the general modeling problem and the basic pipeline in model training and testing.


#### [14:00-16:00] Workshop 2: Generative AI models for omics analysis 

**Workshop instructor: Xingyu Qiao** 

The workshop aims to illustrate the application of pre-trained generative AI models for the classification of cell types and identification of cell markers.


 
