---
title: "Schedule"
author: "Wen Zhong"
date: today
---

<br>

| Date | Time | Location | Classroom | Session | Topic |
|------|------|------|------|------|------|
| Oct. 6, 2025 | 09:00 - 09:50 | Campus US, LiU | [Linden](https://use.mazemap.com/#v=1&campusid=781&zlevel=9&center=15.622763,58.403443&zoom=18&sharepoitype=poi&sharepoi=1001594470) | Session 1. Omics technologies & trends | Lectures 1.1: Course Introduction and  Omics Landscape |
| Oct. 6, 2025 | 10:00 - 10:50 | Campus US, LiU | [Linden](https://use.mazemap.com/#v=1&campusid=781&zlevel=9&center=15.622763,58.403443&zoom=18&sharepoitype=poi&sharepoi=1001594470) |  | Lectures 1.2: Clinical genomics and Scilifelab facilities |
| Oct. 6, 2025 | 11:00 - 11:30 | Campus US, LiU | [Linden](https://use.mazemap.com/#v=1&campusid=781&zlevel=9&center=15.622763,58.403443&zoom=18&sharepoitype=poi&sharepoi=1001594470) |  | Lectures 1.3: Sequencing technologies (WGS, WES, methylation, Long reads, RNA-seq) |
| Oct. 6, 2025 | 11:30 - 12:00 | Campus US, LiU | [Linden](https://use.mazemap.com/#v=1&campusid=781&zlevel=9&center=15.622763,58.403443&zoom=18&sharepoitype=poi&sharepoi=1001594470) |  | Lectures 1.4: Proteome and metabolome technologies |
| Oct. 6, 2025 | 13:00 - 16:00 | Campus US, LiU | [Linden](https://use.mazemap.com/#v=1&campusid=781&zlevel=9&center=15.622763,58.403443&zoom=18&sharepoitype=poi&sharepoi=1001594470) | Workshop 1. Omics in Precision Health | Workshop 1.1 (lecture): Omics data, visualization, processing <br> Workshop 1.2 (hands-on): methylR, completeolink and olinkwrapper |
|------|------|------|------|------|------|------|
| Oct. 7, 2025 | 09:00 - 10:30 | Campus US, LiU | [Bunsen](https://use.mazemap.com/#v=1&campusid=781&zlevel=8&center=15.623239,58.403893&zoom=18&sharepoitype=poi&sharepoi=1001594451) | Session 2. Integrative multi-omics | Lectures 2.1: Single-cell and spatial omics (RNA, ATAC-seq, V(D)J, etc) |
| Oct. 7, 2025 | 10:45 - 12:00 | Campus US, LiU | [Bunsen](https://use.mazemap.com/#v=1&campusid=781&zlevel=8&center=15.623239,58.403893&zoom=18&sharepoitype=poi&sharepoi=1001594451) |  | Lectures 2.2: Integrative multi-omics (Genomics, proteomics, metabolomics) |
| Oct. 7, 2025 | 13:00 - 14:00 | Campus US, LiU | [Bunsen](https://use.mazemap.com/#v=1&campusid=781&zlevel=8&center=15.623239,58.403893&zoom=18&sharepoitype=poi&sharepoi=1001594451) | Workshop 2: Multi-omics integration and feature selection | Workshop 2.1: Single-cell multi-omics |
| Oct. 7, 2025 | 14:00 - 15:00 | Campus US, LiU | [Bunsen](https://use.mazemap.com/#v=1&campusid=781&zlevel=8&center=15.623239,58.403893&zoom=18&sharepoitype=poi&sharepoi=1001594451) |  | Workshop 2.2: General Approaches for integrative multi-omics |
| Oct. 7, 2025 | 15:00 - 16:00 | Campus US, LiU | [Bunsen](https://use.mazemap.com/#v=1&campusid=781&zlevel=8&center=15.623239,58.403893&zoom=18&sharepoitype=poi&sharepoi=1001594451) |  | Workshop 2.3: Integrative multi-omics (MOFA) |
|------|------|------|------|------|------|------|
| Oct. 8, 2025 | 09:00 - 10:30 | Campus US, LiU | [Digitalis](https://use.mazemap.com/#v=1&campusid=781&zlevel=11&center=15.622157,58.403268&zoom=18&sharepoitype=poi&sharepoi=1001593575) | Session 3. AI & ML techniques in biomedical research | Lectures 3.1: Principles for core AI & ML techniques |
| Oct. 8, 2025 | 10:45 - 12:00 | Campus US, LiU | [Digitalis](https://use.mazemap.com/#v=1&campusid=781&zlevel=11&center=15.622157,58.403268&zoom=18&sharepoitype=poi&sharepoi=1001593575) |  | Lectures 3.2: Generative AI for Omics analysis |
| Oct. 8, 2025 | 13:00 - 14:00 | Campus US, LiU | [Digitalis](https://use.mazemap.com/#v=1&campusid=781&zlevel=11&center=15.622157,58.403268&zoom=18&sharepoitype=poi&sharepoi=1001593575) | Workshop 3: AI models for omics analysis | Workshop 3.1: Classical ML methods |
| Oct. 8, 2025 | 14:00 - 16:00 | Campus US, LiUg | [Digitalis](https://use.mazemap.com/#v=1&campusid=781&zlevel=11&center=15.622157,58.403268&zoom=18&sharepoitype=poi&sharepoi=1001593575) |  | Workshop 3.2: Generative AI models for omics analysis |
|------|------|------|------|------|------|------|
| Oct. 9, 2025 | 09:00 - 10:30 | Campus US, LiU | [Papaver](https://use.mazemap.com/#v=1&campusid=781&zlevel=11&center=15.622009,58.403422&zoom=18&sharepoitype=poi&sharepoi=1001593564) | Session 4. Translational Omics & AI research in precision health | Lectures 4.1: AI4health introduction |
| Oct. 9, 2025 | 10:45 - 12:00 | Campus US, LiU | [Papaver](https://use.mazemap.com/#v=1&campusid=781&zlevel=11&center=15.622009,58.403422&zoom=18&sharepoitype=poi&sharepoi=1001593564) |  | Lectures 4.2: Translational AI research |
| Oct. 9, 2025 | 13:00 - 16:00 | Campus US, LiU | [Papaver](https://use.mazemap.com/#v=1&campusid=781&zlevel=11&center=15.622009,58.403422&zoom=18&sharepoitype=poi&sharepoi=1001593564) | Seminar: AI in Translational Research | Seminar: AI in Translational Research |
|------|------|------|------|------|------|------|
| Oct. 10, 2025 | 09:00 - 10:30 | Campus US, LiU | [Björken](https://use.mazemap.com/#v=1&campusid=781&zlevel=10&center=15.622773,58.403433&zoom=18&sharepoitype=poi&sharepoi=1001594471) | Session 5. Applications of AI in Clinical & Digital Health | Lectures 5.1: AI in Clinical & Digital Health |
| Oct. 10, 2025 | 10:45 - 12:00 | Campus US, LiU | [Björken](https://use.mazemap.com/#v=1&campusid=781&zlevel=10&center=15.622773,58.403433&zoom=18&sharepoitype=poi&sharepoi=1001594471) |  | Lectures 5.2: Innovations with AI & Omics |
| Oct. 10, 2025 | 13:00 - 16:00 | Campus US, LiU | [Björken](https://use.mazemap.com/#v=1&campusid=781&zlevel=10&center=15.622773,58.403433&zoom=18&sharepoitype=poi&sharepoi=1001594471) | Group Discussion & Feedback Session | Group Discussion & Feedback Session |
|------|------|------|------|------|------|------|
| Oct. 24, 2025 | 09:00 - 16:00 | Online | | Data project | Group presentation |
: {tbl-colwidths="[10,10,10,10,20,40]"} 

<br/>

Additionally, participants will work in groups on a two-week data project and have an oral presentation on October 24, 2025, providing a practical opportunity to apply the concepts learned during the course.

